//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreysList.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageID { get; set; }
        public int ListingID { get; set; }
        public string Caption { get; set; }
        public byte[] ImageContent { get; set; }
        public string ImageType { get; set; }
        public long ImageSize { get; set; }
        public int ImageHeight { get; set; }
        public int ImageWidth { get; set; }
        public byte[] ThumbContent { get; set; }
        public long ThumbSize { get; set; }
        public int ThumbWidth { get; set; }
        public int ThumbHeight { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Listing Listing { get; set; }
    }
}
